### ISSUE TITLE
бот разучился делать все, кроме удаления каналов или ролей. Фиксани

### ISSUE THREAD

**Issue by DiuDiu227** [GlUTEN-BASH/discord_crasher#2]
Бот не банит, не рассылает всем в лс сообщения, не кикает, короче, только каналы и роли удаляет. Жду фикса

**Comment by GlUTEN-BASH** [comment]
Роли ему дай повыше - раз
Второе - в FAQ написано, куда нужно ставить галочку
Третье - ОН И НЕ ДОЛЖЕН В ЛС РАССЫЛАТЬ СООБЩЕНИЯ, ПРЕДСТАВЛЯЕШЬ?
Четвертое - раз закрыл, как-то пофиксил проблему?

**Comment by GlUTEN-BASH** [comment]
В следующий раз пишешь иссью - прилагай как баг проявляется, видос с ним, саму ошибку в консоли. Если что-то менял в коде и после этого не работает - кидай что менял
